name: job_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #default
  cupertino_icons: ^1.0.2
  #for state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  #for network
  http: ^0.13.6
  #for current location
  geolocator: ^9.0.2
  model_viewer_plus: ^1.5.0
  easy_localization: ^3.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  inview_notifier_list: ^3.0.0
  flutter_yandex_ads: ^1.0.0+1

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
